#!/usr/bin/env python

import sys
import lxml.html
from os.path import join
from pathlib import Path


PAIRS = [
    ('//img',  'src'),
    ('//a',    'href'),
    ('//link', 'href'),
]


def prefix_link(link, p):
    if link.startswith('/') and not link.startswith('//'):
        return join(p, link[1:])
    return link


def main(src, prefix):
    src = Path(src)
    for file in src.rglob('*.html'):
        if file.is_dir():
            continue

        tmp = Path(str(file) + '.tmp')
        tmp.touch()

        with file.open('r') as fp:
            tree = lxml.html.parse(fp)
            for query, attr in PAIRS:
                for e in tree.xpath(query):
                    link = e.get(attr)
                    if link is None:
                        continue
                    e.attrib[attr] = prefix_link(link, prefix)

        with tmp.open('wb') as w:
            tree.write(w)
        tmp.rename(file)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
